CHANGELOG.md, lib/assets/javascripts/unpoly/browser.js.coffee, lib/assets/javascripts/unpoly/log.js.coffee, lib/assets/javascripts/unpoly/proxy.js.coffee, lib/assets/javascripts/unpoly/syntax.js.coffee, spec_app/spec/javascripts/up/flow_spec.js.coffee, spec_app/spec/javascripts/up/link_spec.js.coffee, spec_app/spec/javascripts/up/modal_spec.js.coffee, spec_app/spec/javascripts/up/motion_spec.js.coffee, spec_app/spec/javascripts/up/popup_spec.js.coffee
Fix Unpoly and its specs for IE9 and IE10 by marking more specs as "only with CSS transitions enabled". and polyfilling `window.console` and several properties (`log`, `debug`, `info`,  `warn`, `error`, `group`, `groupCollapsed`, `groupEnd`).
+ Typo fix
=> Fix things for IE

CHANGELOG.md, lib/assets/javascripts/unpoly/modal.js.coffee, lib/assets/javascripts/unpoly/popup.js.coffee, spec_app/spec/javascripts/up/modal_spec.js.coffee, spec_app/spec/javascripts/up/popup_spec.js.coffee
Fix a bug where auto-closed modals and popups would overwrite a changed browser location with their cached "covered URL"
=> Autoclose URL issue

CHANGELOG.md, lib/assets/javascripts/unpoly/modal.js.coffee, lib/assets/javascripts/unpoly/util.js.coffee, spec_app/Gemfile.lock, spec_app/spec/javascripts/up/modal_spec.js.coffee
By setting `up.modal.config.closable = false`, Unpoly will not render a close button inside a modal and will neither close a modal when the backdrop is clicked.
=> Introduce up.modal.config.closable=true

CHANGELOG.md, README_RAILS.md, lib/unpoly/rails/request_echo_headers.rb, lib/unpoly/rails/request_method_cookie.rb, lib/unpoly/rails/version.rb, spec_app/Gemfile.lock
Rails 5 removed `before_filter`, so unpoly-rails now uses `before_action` if available.
`before_filter` will be used on older Railses.
=> Add support for Rails 5

lib/assets/stylesheets/unpoly/toast.sass
This fixes a Sass deprecation warning.
```
DEPRECATION WARNING on line 20 of (...)/gems/unpoly-rails-0.50.0/lib/assets/stylesheets/unpoly/toast.sass:
The operation `#333 plus 80` is deprecated and will be an error in future versions.
Consider using Sass's color functions instead.
http://sass-lang.com/documentation/Sass/Script/Functions.html#other_color_functions
```
The resulting color is slightly different, but I guess it's good enough as this currently affects only error messages.
=> Avoid Sass deprecation warning for "plus" operator

lib/assets/javascripts/unpoly/util.coffee, spec_app/spec/javascripts/up/motion_spec.js.coffee
`uniq` from 0.55 won't work in IE11 or Edge, as `new Set(array)` is unsupported. This fixes the issue.
Also fixes an unrelated spec which failed in IE when comparing offsets of cloned elements.
=> Fix up.util.uniq for IE and Edge

lib/assets/javascripts/unpoly-bootstrap3/feedback-ext.coffee
I noticed that the property got renamed in 06134f0
=> fix rename of feedback property navSelectors->navs introduced in 06134f0

lib/assets/javascripts/unpoly/syntax.coffee.erb
I fixed a typo in line 8077 of dist/unpoly.js.
=> Fix a typo in the documentation

lib/assets/javascripts/unpoly/fragment.coffee.erb, lib/assets/javascripts/unpoly/link.coffee.erb, lib/assets/javascripts/unpoly/syntax.coffee.erb
There is also a typo in <https://unpoly.com/tutorial> that you might want to fix yourself (tutorial page does not seem to be part of the repo).
> Have you noticed how noticed how pages fade in
=> Fix some typos in documentation

dist/unpoly.js, lib/assets/javascripts/unpoly/modal.coffee.erb
Currently, https://unpoly.com/up.modal.follow contains a 404 link to /a.up-modal. 
In this pull request these links have been replaced by /a-up-modal.
=> Bugfixes in link to /a-up-modal

lib/assets/javascripts/unpoly/modal.coffee.erb, spec_app/spec/javascripts/up/modal_spec.js.coffee
I don't use Jasmine much in my own projects (to the credit of Unpoly eliminating a lot of custom JS) so hopefully I didn't butcher the spec.
Let me know if you think anything needs to be changed.
=> [up-modal] should respect cache setting

Rakefile
The `dist/unpoly.js` output contains UTF-8 characters that trigger the
following error when performing `assets:validate`.
ArgumentError: invalid byte sequence in US-ASCII
I'm not aware of any drawbacks to setting this.
=> Set utf-8 encoding during asset validation

lib/assets/javascripts/unpoly/element.coffee, lib/assets/javascripts/unpoly/fragment.coffee, spec_app/spec/javascripts/up/element_spec.coffee, spec_app/spec/javascripts/up/fragment_spec.js.coffee
Classes with colon's are permitted if the colon is escaped (ie. Tailwind utility classes).
~Appears to break this spec at this line, but I can't seem to figure out why after going through the debug loop. Any thoughts?~ I think you were right and it was browser focus.
=> Escape class name when building target

lib/assets/javascripts/unpoly/log.coffee
Instead of listening for when the framework has booted, listen for the event
that is fired when the application is booted and the DOM is ready.
At this stage, any changes to up.log.config would be completed, allowing the
banner to be disabled if desired.
Closes #157
=> Print banner after booting app

lib/assets/javascripts/unpoly/protocol.coffee
It seems that the date used in the example is incorrect. When I enter it at https://www.unixtimestamp.com/index.php, I get Wed Dec 23 2020 13:40:18 GMT+0000.
=> Use correct date in `X-Up-Reload-From-Time` example

lib/assets/javascripts/unpoly/classes/request.coffee, lib/assets/javascripts/unpoly/fragment.coffee
Clarify that the `up-source` attribute needs to be applied to the element being reloaded via `up.reload`.
=> Documentation fixes

lib/assets/javascripts/unpoly/log.coffee
Instead of listening for when the framework has booted, listen for the event
that is fired when the application is booted and the DOM is ready.
At this stage, any changes to up.log.config would be completed, allowing the
banner to be disabled if desired.
Backport to 1.x release branch.
=> [v1 backport] Print banner after booting app

lib/assets/javascripts/unpoly/link.coffee
I'm not sure if it should be mentioned that this is a browser limitation.
Came out of #195
=> Document method wrapping for non-GET/POST request

lib/assets/javascripts/unpoly/layer.coffee
Explicitly document which style of separation is used for multiple attribute arguments.
I can never remember if it's space or comma separated.
=> Document separation of multiple attribute arguments

src/unpoly/pages/focus-option.md
Very small typo, but it confused me because the word "list" is (correctly) used later in the sentence.
=> Fix small typo

spec/unpoly/classes/request_spec.coffee, spec/unpoly/network_spec.js, src/unpoly/classes/request.js, src/unpoly/classes/request/xhr_renderer.js
Add up.Request#xhr property which returns the not yet sent XMLHttpRequest object.
With this, it's possible to access the xhr in a [up:request:load](https://unpoly.com/up:request:load) event handler through the event.request.xhr property.
One use case is to add xhr event listeners. For example this is required to listen on upload progress events.
See #435.
=> Add xhr property to Request

spec/unpoly/element_spec.coffee, src/unpoly/element.js
Update regular expression used for escaping class selector to escape any non-alphanumeric/hyphen characters.
Closes #492
=> Update `up.element.classSelector` to escape non-alphanumeric/hyphen enabling support for more Tailwind JIT syntax

src/unpoly/pages/watch-options.md
I believe it should point to [this page](https://unpoly.com/a-up-follow#up-feedback) instead. But it could be suitable to [this page](https://unpoly.com/up.feedback). WDYT?
=> Fix link to `[up-feedback]` attribute

src/unpoly/form.js
Submit buttons can be located outside of the `<form>` in question, but can still be a part of the form through the `form` attribute.
Make sure to detect this situation and submit the correct name/value pair in this case as well.
---
I am not sure this is the correct approach as I don't know much about browsers and JS, but it works for me.
=> Submit name/value from buttons outside the form

src/unpoly/pages/url-patterns.md
Added to and refined the existing URL patterns documentation a fair bit.
- Added examples for all sections
- Made existing URL patterns more consistent throughout the document
- Misc. refinements and improvements
- Moved the numeric/digit wildcard matching section just under the wildcard section.
Pleases give the JavaScript examples particular scrutiny during your review.
Thanks for the great project. Unpoly gives my Django projects super powers from the future! :smiley:
=> Add examples and refine URL patterns docs

spec/unpoly/element_spec.coffee, src/unpoly/element.js
When checking if in subtree where the root is `HTMLFormElement`, there is a chance that `root.contains` is actually another form element, and not the function `contains`.
To work around this, use the prototype function directly from Node.
Closes #507
=> Use contains function from Node prototype

src/unpoly/event.js
I was searching how to achieve something like `return false` in jQuery within `up.on`. And maybe it would helped me if there was an explizit link to `up.event.halt`.
Note: I was not able to test the documentation.
=> [docs] Add a link from up.on to up.event.halt

src/unpoly/pages/dependent-fields.md
The first code block on the `Dependent Fields` page had a label with the `for` attribute pointing to the id "content", which was used nowhere. 
Fixed what I believe to be a typo (from looking around other files and references within the same file)
=> Changed typo in label 'for' value

src/unpoly/form.js
Hey! 
what a great library!
I found a typo while reading the documentations.
=> fix typo in form.js 'hader' => 'header'

src/unpoly/pages/predefined-transitions.md
I noticed that the description of predefined transitions do not match examples.
I suppose that was copy-paste error during docs refactoring 5b87174 so I changed it to more probable fragment.
=> Fix documentation on predefined transitions

src/unpoly/viewport.sass
The current implementation of `.up-focus-hidden:focus-visible` can cause outline flickering in projects which transition the outline color.
The previous style of `outline: none` expands into the following style definitions.
```css
outline-color: initial;
outline-style: none;
outline-width: initial;
```
Unfortunately, `outline-color: initial` means `outline-color: currentColor`.
This causes issues with application which transition the `outline-color` property on elements.
If an `.up-focus-visible` element is `:focus-visible` only for a brief moment (e.g. when clicking a link, Chrome applies `:focus-visible` just to remove it right after), the element's transition rules will then cause a transition of `outline-color` starting with `currentColor`. This is usually not desired and looks like a …
=> Fix flickering focus outline for .up-focus-hidden elements

spec/unpoly/link_spec.js.coffee, src/unpoly/link.js
There is a (new?) behavior in browsers that I've noticed: When preloading a link with a `tel`-`href`, the browser issues a warning. In Chrome, the `tel`-link is even visible through the browser's address bar. I don't know if this is another potential problem that should be investigated.
=> Add tel links to noFollowSelectors

src/unpoly/viewport.sass
I believe we should be using `overflow-y: clip` instead of `overflow-y: hidden` when the body scrollbar is hidden.
Using `clip` allows elements with `position: sticky` to stay at their sticky position. With `hidden`, a sticky toolbar would disappear when the user scrolled down and opens a modal.
Browsers which don't support `clip` ([basically just Safari <16](https://caniuse.com/mdn-css_types_overflow_clip)) would fall back to using `hidden`.
=> Use "overflow-y: clip" instead of "overflow-y: hidden" when scrollbar is hidden

src/unpoly/pages/predefined-transitions.md
I believe these are intended to be `exits`.
=> Fix spelling in predefined transitions doc
